import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ReactQueryProvider } from "@/lib/ReactQueryProvider";
import { startSocket } from "@/ws";
import { NextAuthProvider } from "@/lib/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });
export const socket = startSocket("http://localhost:3333", 3010);

socket?.on("connect_error", (err) => {
  console.log(err.message); // prints the message associated with the error
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <Header />
            {children}
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
